---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install packages
  package:
    name: "{{ unbound_packages }}"

- name: Create configuration from template
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_etc_dir }}/unbound.conf"
    mode: '0644'
  notify: Restart unbound

- name: Create local configuration file
  template:
    src: local.conf.j2
    dest: "{{ unbound_confd_dir }}/local.conf"
    mode: '0644'
  notify: Restart unbound

- name: Download the list of root servers
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: "{{ unbound_etc_dir }}/root.hints"
    mode: '0644'
  notify: Restart unbound

- name: Start/enable the daemon
  systemd:
    name: unbound
    enabled: true
    state: started

- name: Open firewall port
  include_role:
    name: firewall
  vars:
    firewall_ports: "{{ unbound_firewall_ports }}"
  when: unbound_firewall|bool
