---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Installation phase
  ansible.builtin.include_tasks: install.yml

- name: Configuration phase
  ansible.builtin.include_tasks: config.yml
