---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    unbound_do_ip6: no
    unbound_firewall: False
    unbound_custom_records: [{'name': 'server1.example.com', 'ip': '192.168.56.100', 'cnames': ['test.example.com', 'test1.example.com']}, {'name': 'server2.example.com', 'ip': '192.168.56.101'}]
  tasks:
    - name: Include role 'ansible-role-unbound'
      ansible.builtin.include_role:
        name: ansible-role-unbound
