---

- name: Converge
  hosts: all
  vars:
    unbound_do_ip6: false
    unbound_firewall_ports:
      - port: '53'
        proto: tcp
      - port: '53'
        proto: udp
  tasks:
    - name: Include role 'ansible-role-unbound'
      include_role:
        name: ansible-role-unbound
